name: Deploy to Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  FIREBASE_PROJECT_ID: 'static-sites-257923'

jobs:
  lint-test-deploy:
    name: Lint, Test & Deploy
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://job-finder-staging.web.app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Unit tests
        run: npm run test:unit

      - name: Get version
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Build for staging
        run: npm run build:staging
        env:
          NODE_ENV: production
          VITE_APP_VERSION: ${{ steps.version.outputs.version }}

      - name: Verify build
        run: |
          if [ ! -d "dist" ] || [ ! -f "dist/index.html" ]; then
            echo "❌ Build verification failed"
            exit 1
          fi
          echo "✅ Build verification successful"
          du -sh dist

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: ${{ env.FIREBASE_PROJECT_ID }}
          target: staging

      - name: Verify deployment
        run: |
          echo "Waiting for deployment..."
          sleep 5
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://job-finder-staging.web.app)
          if [ "$HTTP_CODE" = "200" ]; then
            echo "✅ Staging deployed successfully"
          else
            echo "⚠️ HTTP $HTTP_CODE - may still be propagating"
          fi

      - name: Deployment summary
        if: always()
        run: |
          echo "## 🚀 Staging Deployment" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **URL**: https://job-finder-staging.web.app" >> $GITHUB_STEP_SUMMARY
          echo "- **Custom Domain**: https://job-finder-staging.joshwentworth.com" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Actor**: @${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
