name: PR Checks

on:
  pull_request:
    branches:
      - staging
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript type checking
        run: npx tsc --noEmit

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm test
        env:
          CI: true

      - name: Build application
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: "demo-api-key"
          VITE_FIREBASE_AUTH_DOMAIN: "demo-project.firebaseapp.com"
          VITE_FIREBASE_PROJECT_ID: "demo-project"
          VITE_FIREBASE_STORAGE_BUCKET: "demo-project.appspot.com"
          VITE_FIREBASE_MESSAGING_SENDER_ID: "123456789"
          VITE_FIREBASE_APP_ID: "1:123456789:web:abcdef"
          VITE_API_BASE_URL: "http://localhost:5001"

      - name: Comment PR with build size
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const { execSync } = require('child_process');
            const fs = require('fs');
            const distSize = execSync('du -sh dist').toString().split('\t')[0];

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ Build successful!\n\n📦 Bundle size: ${distSize}`
            });
