name: PR Checks

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  statuses: write

env:
  NODE_VERSION: '20'

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run type-check

      - name: Check code formatting
        run: npm run format:check

      - name: Run unit tests
        run: npm run test:unit
        env:
          CI: true

      - name: Build verification
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: "demo-api-key"
          VITE_FIREBASE_AUTH_DOMAIN: "demo-project.firebaseapp.com"
          VITE_FIREBASE_PROJECT_ID: "demo-project"
          VITE_FIREBASE_STORAGE_BUCKET: "demo-project.appspot.com"
          VITE_FIREBASE_MESSAGING_SENDER_ID: "123456789"
          VITE_FIREBASE_APP_ID: "1:123456789:web:abcdef"
          VITE_FIRESTORE_DATABASE_ID: "portfolio"
          VITE_API_BASE_URL: "http://localhost:5001"

      - name: Comment PR with results
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const { execSync } = require('child_process');
            const fs = require('fs');
            
            let distSize = 'N/A';
            try {
              distSize = execSync('du -sh dist 2>/dev/null').toString().split('\t')[0];
            } catch (e) {
              console.log('Could not get dist size');
            }

            const status = '${{ job.status }}';
            const emoji = status === 'success' ? '✅' : '❌';
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${emoji} **PR Checks ${status}**\n\n📦 Bundle size: ${distSize}\n\n*Merge when checks pass*`
            });
