name: Version Bump

on:
  push:
    branches:
      - staging
    paths-ignore:
      - 'package.json'
      - 'package-lock.json'

env:
  NODE_VERSION: '20'

jobs:
  version-bump:
    name: Auto Bump Version
    runs-on: ubuntu-latest
    # Only run if the commit was not made by github-actions bot
    if: "!contains(github.event.head_commit.message, '[skip-version]') && github.event.head_commit.author.name != 'github-actions[bot]'"

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get current version
        id: current_version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $CURRENT_VERSION"

      - name: Bump patch version
        id: bump
        run: |
          npm version patch -m "chore(release): bump version to %s [skip-version]" --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Bumped to version: $NEW_VERSION"

      - name: Update package-lock.json
        run: npm install --package-lock-only

      - name: Commit version bump
        run: |
          git add package.json package-lock.json
          git commit -m "chore(release): bump version to ${{ steps.bump.outputs.new_version }} [skip-version]"

      - name: Push changes
        run: |
          git push origin staging

      - name: Create version tag
        run: |
          git tag -a "v${{ steps.bump.outputs.new_version }}" -m "Version ${{ steps.bump.outputs.new_version }}"
          git push origin "v${{ steps.bump.outputs.new_version }}"

      - name: Summary
        run: |
          echo "## Version Bump Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Previous version**: ${{ steps.current_version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **New version**: ${{ steps.bump.outputs.new_version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Tag created**: v${{ steps.bump.outputs.new_version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch**: staging" >> $GITHUB_STEP_SUMMARY
